### ISSUE TITLE
Keep dict insertion order during `dump`

### ISSUE THREAD

**Issue by h-vetinari** [bobfang1992/pytomlpp#48] opened 2021-05-19 12:45 UTC
Hey, thanks for this library!

I just followed down the rabbit-hole of figuring out what would be necessary to maintain insertion order, and basically, this is blocked on https://github.com/marzer/tomlplusplus/issues/28 / https://github.com/marzer/tomlplusplus/issues/62.

I just thought I'd open an issue here for someone else who might be wondering about this (and yes, I'm keen to see this resolved, even if it means fixing it on the tomlplusplus side). 🙃

**Comment by marzer** [comment] 2021-05-19 14:43
> fixing it on the tomlplusplus side

Fixing it implies that it's broken. It's not. It disregards order on purpose, as I justify quite comprehensively in the thread you linked. If you want this 'fixed', fix it in python, as toml++ will stay the way it is for the forseeable future.

**Comment by bobfang1992** [comment] 2021-05-19 15:05
I'd rather not change tomlplusplus's behaviour unless there is a compelling reason not to. Could you give me some reason?

**Comment by bobfang1992** [comment] 2021-05-19 15:11
Or can it be done with some params to control this behaviour instead of by default?

**Comment by marzer** [comment] 2021-05-19 15:17
@bobfang1992 there's no way to do this C++-side without nontrivial modification to TOML++. The root of the issue is that the lib uses std::map to take advantage of C++17's heterogeneous lookup, a side effect being that std::map doesn't track insertion order, and iteration is simply ordered according to key, so things get re-ordered alphabetically.

Theoretically, If I made the underlying map configurable, a user could swap it out for something that maintained insertion order, but it would also need to support heterogeneous lookup for it to compile. To my knowledge nothing like that exists (though it has been a while since I looked, to be honest).

**Comment by bobfang1992** [comment] 2021-05-20 08:10
cool thanks for the clarification. I will keep this open so people can easily spot this issue if they wanted the same thing. Seems nothing can be done on pytomlpp's side.

**Comment by h-vetinari** [comment] 2021-05-20 08:52
> Seems nothing can be done on pytomlpp's side.

It's not completely impossible (as hardly anything is...) - `py_dict_to_toml_table` could keep track of insertion order and save that information in a way that it can get reused when writing, but IMO it would be much more desirable to implement this on the toml++ side.

**Comment by bobfang1992** [comment] 2021-11-18 00:01
closing on this as we do not plan to support it.

**Closed by bobfang1992** 2021-11-18 00:01 UTC

**Comment by pwwang** [comment] 2022-05-06 23:41
Here is an reference:
https://github.com/pwwang/toml-bench#testdumpkeysorder
even though it's not in the plan

**Comment by bobfang1992** [comment] 2022-11-16 15:23
@yuezhihan Well in general in open source world there is a saying "be the change you want". I'd encourage you to take a look at the source code of this repo first, and see if we can do it here. It is a relatively simple code base and we might be able to do it here without touching the underlying tomlpp library.

**Comment by h-vetinari** [comment] 2022-11-17 01:34
> I'd encourage you to take a look at the source code of this repo first, and see if we can do it here.

I did take a look at the time, and I don't think it's possible without either:
* carrying insertion order metadata in pytomlpp (presumed undesirable)
* fixing it in toml++ (runs into limitations of available C++ containers vs. desired performance characteristics)
